cmake_minimum_required(VERSION 3.16)
project(Freecam LANGUAGES CXX ASM_MASM)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

file(GLOB_RECURSE SRC CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h
)

add_subdirectory(extern)

add_library(${PROJECT_NAME} SHARED
    ${SRC}
    src/core/hook/daytime_update.asm
    src/core/hook/follow_camera.asm
    src/core/hook/camera_position.asm
)

target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src)

target_link_libraries(${PROJECT_NAME} PRIVATE extern::all)

set(GAME_DIR "" CACHE PATH "Path to game folder")
if(GAME_DIR)
    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
        $<TARGET_FILE:${PROJECT_NAME}>
        "${GAME_DIR}"
    )
endif()
